version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: documentmgn-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: documentmgn
    ports:
      - "3308:3308"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: